package net.ausiasmarch.calculadoraCal.gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import net.ausiasmarch.calculadoracal.mod.Calorias;
import net.ausiasmarch.calculadoracal.mod.TipoActividad;
import net.ausiasmarch.common.Convert;

/**
 *
 * @author a006265699q
 */
public class Main extends javax.swing.JFrame {

        // Delaramos un objeto 
    private final Calorias calorias;
    
    /**
     * Creates new form Main2
     */
    public Main() {
        initComponents();

        jComboBoxActividad.addItem(TipoActividad.SEDENTARIO.toString());
        jComboBoxActividad.addItem(TipoActividad.LIGERA.toString());
        jComboBoxActividad.addItem(TipoActividad.MODERADA.toString());
        jComboBoxActividad.addItem(TipoActividad.INTENSA.toString());
        jComboBoxActividad.addItem(TipoActividad.MUY_INTENSA.toString());

        // creamos el objeto
        calorias = new Calorias();

        iniciaForm();
    }

    /**
     * Inicia el form
     */
    private void iniciaForm() {
        getContentPane().setBackground(Color.WHITE);
        setSize(441, 680);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelGenero = new javax.swing.JPanel();
        jRadioButtonMujer = new javax.swing.JRadioButton();
        jRadioButtonHombre = new javax.swing.JRadioButton();
        jComboBoxActividad = new javax.swing.JComboBox<>();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMetabolismoBasal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMantener = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAdelgazar = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo de de calorías");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanelDatos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelDatos.setMinimumSize(new java.awt.Dimension(441, 660));
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 153));
        jLabel9.setText("Calculadora de Calorias");
        jPanelDatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 13, 333, 38));

        jPanelGenero.setBackground(new java.awt.Color(204, 204, 255));
        jPanelGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Género", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(102, 0, 204))); // NOI18N

        jRadioButtonMujer.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButtonMujer.setText("Mujer");

        jRadioButtonHombre.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButtonHombre.setSelected(true);
        jRadioButtonHombre.setText("Hombre");
        jRadioButtonHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGeneroLayout = new javax.swing.GroupLayout(jPanelGenero);
        jPanelGenero.setLayout(jPanelGeneroLayout);
        jPanelGeneroLayout.setHorizontalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneroLayout.createSequentialGroup()
                .addComponent(jRadioButtonMujer)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonHombre))
        );
        jPanelGeneroLayout.setVerticalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneroLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMujer)
                    .addComponent(jRadioButtonHombre)))
        );

        jPanelDatos.add(jPanelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 99, -1, -1));

        jComboBoxActividad.setBackground(new java.awt.Color(204, 204, 255));
        jComboBoxActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actividad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(102, 0, 153))); // NOI18N
        jComboBoxActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActividadActionPerformed(evt);
            }
        });
        jPanelDatos.add(jComboBoxActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 91, 175, 63));

        jLabelEdad.setText("Edad");
        jPanelDatos.add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 193, -1, -1));
        jPanelDatos.add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 185, 174, 32));

        jLabel2.setText("Peso");
        jPanelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 245, -1, -1));
        jPanelDatos.add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 236, 174, 33));

        jLabel5.setText("años");
        jPanelDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 193, -1, -1));

        jLabel4.setText("kg");
        jPanelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 245, -1, -1));
        jPanelDatos.add(jTextFieldAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 298, 174, 33));

        jLabel3.setText("Altura");
        jPanelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 307, -1, -1));

        jLabel6.setText("cm");
        jPanelDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 299, -1, -1));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        jPanelDatos.add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 349, -1, -1));

        jLabel1.setText("MetabolismoBasal");
        jPanelDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jTextFieldMetabolismoBasal.setBackground(new java.awt.Color(255, 255, 204));
        jPanelDatos.add(jTextFieldMetabolismoBasal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 137, 33));

        jLabel7.setText("Calorias para mantener");
        jPanelDatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jTextFieldMantener.setBackground(new java.awt.Color(255, 255, 204));
        jPanelDatos.add(jTextFieldMantener, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 137, 33));

        jLabel8.setText("Calorias para adelgazar");
        jPanelDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jTextFieldAdelgazar.setBackground(new java.awt.Color(255, 255, 204));
        jPanelDatos.add(jTextFieldAdelgazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 136, 32));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelDatos.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 87, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 0, 153));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 153)));
        jPanelDatos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 410, 395, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHombreActionPerformed

    private void jComboBoxActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActividadActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // 1) Declaramos todas las variables de entrada y salida
        int edad, altura;
        double peso;
        boolean mujer, hombre;
        String actividad;
        boolean genero;
        double metabolismoBasal, mantener, adelgazar;
        double metabolismo;

        StringBuilder sb = new StringBuilder();

        // 2) Limpiamos los campos de datos de salida o resultados
        jTextFieldMetabolismoBasal.setText("");
        jTextFieldMantener.setText("");
        jTextFieldAdelgazar.setText("");

        // 3) Obtenemos y validamos los datos de entrada
        if (!Convert.isValidDouble(jTextFieldPeso.getText())) {
            sb.append(" - Introduce el peso.\n");
        }
        if (!Convert.isValidInt(jTextFieldEdad.getText())) {
            sb.append(" - Introduce la edad.\n");
        }
        if (!Convert.isValidInt(jTextFieldAltura.getText())) {
            sb.append(" - Introduce la altura.\n");
        }

        // Si hay errores de entrada (sintacticos)
        if (sb.length() > 0) {
            mensaje(sb.toString());
            return;                    // no continuamos
        }

        // 4) Hacemos las conversiones de datos numericos
        edad = Convert.parseInt(jTextFieldEdad.getText());
        altura = Convert.parseInt(jTextFieldAltura.getText());
        peso = Convert.parseDouble(jTextFieldPeso.getText());

        // 5) Pasamos los datos de entrada a calorias
        // Los numericos
        calorias.setEdad(edad);
        calorias.setPeso(peso);
        calorias.setAltura(altura);

        //los booleanos
        calorias.setMujer(jRadioButtonMujer.isSelected());
        calorias.setHombre(jRadioButtonHombre.isSelected());
        calorias.setActividad(jComboBoxActividad.getSelectedItem().toString());

        if (calorias.validate() == false) {

            sb.append(calorias.getMensaje());
            // Mostramos los mensajes de errorCorazón
            mensaje(sb.toString());
            return;
            // y no continuamos
        }

        // 6) Obtenemos cálculos desde el objeto calorias
        metabolismoBasal = calorias.metabolismoBasal();
        mantener = calorias.mantener();
        adelgazar = calorias.adelgazar();

        // 7) Mostramos los resultados con formato en los campos de salida
        jTextFieldMetabolismoBasal.setText(Convert.format(metabolismoBasal, 2));
        jTextFieldMantener.setText(Convert.format(mantener, 2));
        jTextFieldAdelgazar.setText(Convert.format(adelgazar, 2));

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

      private void mensaje(String mensaje) {
        mensaje = "\n" + mensaje + "\n";
        JOptionPane.showMessageDialog(this, mensaje,
                " Se han encontrado los siguientes errores", JOptionPane.ERROR_MESSAGE);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxActividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelGenero;
    private javax.swing.JRadioButton jRadioButtonHombre;
    private javax.swing.JRadioButton jRadioButtonMujer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAdelgazar;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldMantener;
    private javax.swing.JTextField jTextFieldMetabolismoBasal;
    private javax.swing.JTextField jTextFieldPeso;
    // End of variables declaration//GEN-END:variables
}
